version: "3"
services:
  https:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - django
    restart: always
    depends_on:
      - django
    environment:
      CLIENT_MAX_BODY_SIZE: 0
      DOMAINS: 'storage.sirileepage.com -> http://django'
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
  django:
    build: ./
    image: sirily11/storage-management-system
    env_file:
      - .env
    ports:
      - '3000:80'
    stdin_open: true
    tty: true

  test:
    build: ./
    image: sirily11/storage-management-system
    stdin_open: true
    tty: true
    command: >
      sh -c "coverage run --source='.' manage.py test && coverage html"
    environment:
      - local=1
