# Generated by Django 2.2 on 2019-04-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_takes', models.FloatField(default=0)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Selection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.User')),
            ],
        ),
    ]
