# Generated by Django 2.2 on 2019-04-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_from_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image_url',
            new_name='image',
        ),
    ]
