# Generated by Django 2.2 on 2019-04-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190415_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
