# Generated by Django 2.2 on 2019-04-15 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SurveyUser',
        ),
        migrations.AlterField(
            model_name='userselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
