# Generated by Django 2.2 on 2019-04-15 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20190415_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser'),
        ),
    ]
