# Generated by Django 2.2 on 2019-04-15 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190415_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='survey.Question'),
        ),
    ]
