# Generated by Django 2.2 on 2019-04-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glacier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(default='', max_length=1024, verbose_name='AWS Access ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('vault_name', models.CharField(default='', max_length=1024, verbose_name='Vault Name')),
                ('glacier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to='glacier.Glacier', verbose_name='Glacier account')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=1024)),
                ('file_size', models.FloatField()),
                ('achieve_id', models.CharField(max_length=1024)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='glacier.Vault', verbose_name='File')),
            ],
        ),
    ]
