# Generated by Django 2.2 on 2019-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glacier',
            name='access_id',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='AWS Access ID'),
        ),
    ]
