# Generated by Django 2.2 on 2019-04-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier', '0002_auto_20190420_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vault',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.FloatField(verbose_name='File Size (bytes)'),
        ),
    ]
