# Generated by Django 2.2 on 2019-04-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glacier', '0003_auto_20190420_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vault',
            old_name='vault_name',
            new_name='VaultName',
        ),
    ]
