# Generated by Django 2.2 on 2019-04-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier', '0004_auto_20190420_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='VaultName',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Vault Name'),
        ),
    ]
