# Generated by Django 2.2 on 2019-04-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glacier', '0005_auto_20190420_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_size',
            new_name='filesize',
        ),
    ]
