# Generated by Django 2.2 on 2019-04-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glacier', '0006_auto_20190421_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='achieve_id',
            new_name='achieveId',
        ),
    ]
