# Generated by Django 3.0.8 on 2020-07-01 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='No content here', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Book', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Book Shelf 1', max_length=1024)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('name', models.CharField(default='', help_text='Please Enter your item name', max_length=1024, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, help_text='Please enter your item description', max_length=1024, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('qr_code', models.CharField(blank=True, max_length=10008, null=True)),
                ('column', models.IntegerField(default=1)),
                ('row', models.IntegerField(default=1)),
                ('unit', models.CharField(choices=[('USD', '美元'), ('HDK', '港币'), ('CNY', '人民币')], default='USD', max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_management.Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_management.Category')),
                ('detail_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_management.DetailPosition')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='China', max_length=128)),
                ('city', models.CharField(default='Shenzhen', max_length=128)),
                ('street', models.CharField(blank=True, default='Qian Hai Lu', max_length=128, null=True)),
                ('building', models.CharField(blank=True, default='Tian Lang Feng Qing', max_length=128, null=True)),
                ('unit', models.CharField(blank=True, default='Tian Qi Yuan', max_length=128, null=True)),
                ('room_number', models.CharField(default='605', max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No content here', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Face', max_length=128, null=True)),
                ('image', models.ImageField(upload_to='item-image', verbose_name='Item Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storage_management.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(default='', max_length=1024)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage_management.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_management.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_management.Series'),
        ),
    ]
