# Generated by Django 2.2.2 on 2019-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
