# Generated by Django 2.2.2 on 2019-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0002_item_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='title',
            field=models.CharField(blank=True, default='Face', max_length=128, null=True),
        ),
    ]
