# Generated by Django 2.2.2 on 2019-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0003_itemimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Book', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
