# Generated by Django 3.0.8 on 2020-07-06 17:02

from django.db import migrations, models
import storage_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0003_auto_20200705_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to=storage_management.models.upload_location, verbose_name='Item Image'),
        ),
    ]
