# Generated by Django 2.2.2 on 2019-06-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0004_auto_20190624_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='column',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='row',
            field=models.IntegerField(default=1),
        ),
    ]
