# Generated by Django 3.2.7 on 2021-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0004_auto_20200706_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('USD', '美元'), ('HKD', '港币'), ('CNY', '人民币')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(blank=True, default='Some Building', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_number',
            field=models.CharField(default='Some RM Number', max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, default='Some Street', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='unit',
            field=models.CharField(blank=True, default='Some Unit', max_length=128, null=True),
        ),
    ]
