# Generated by Django 2.2.2 on 2019-06-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0006_auto_20190624_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, default='No content here', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(default='No content here', max_length=128, unique=True),
        ),
    ]
