# Generated by Django 2.2.2 on 2019-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0008_auto_20190707_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
