# Generated by Django 2.2.2 on 2019-07-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0009_auto_20190707_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=123),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
