# Generated by Django 2.2.2 on 2019-07-07 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0010_auto_20190707_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField(default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage_management.Item')),
            ],
        ),
    ]
