# Generated by Django 2.2.2 on 2019-07-08 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0011_itemfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='itemfile',
            name='file',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
