# Generated by Django 2.2.2 on 2019-07-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0012_auto_20190708_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
