# Generated by Django 2.2.4 on 2019-09-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0013_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Please enter your item description', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', help_text='Please Enter your item name', max_length=1024, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('USD', '美元'), ('HDK', '港币'), ('CNY', '人民币')], default='USD', max_length=10),
        ),
    ]
