# Generated by Django 3.0.1 on 2019-12-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0015_detailposition_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
