# Generated by Django 3.0.4 on 2020-06-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_management', '0016_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
